language: python
python:
  - "3.5"
  - "3.6"
install:
  - pip install tox
  - pip install travis-tox
  - pip install -e .
script:
  - tox --skip-missing-interpreters
after_success:
  - coverage report
  - coveralls
  
